### PR TITLE
Update to latest 

### PR DESCRIPTION
**Pull request by jan-janssen**
Current DAMASK issue: 
```
 <<<+-  parallelization init  -+>>>
 MPI processes:   1
 Could not determine value of $DAMASK_NUM_THREADS
 DAMASK_NUM_THREADS:  1

 <<<+-  DAMASK_interface init  -+>>>
 
      _/_/_/      _/_/    _/      _/    _/_/      _/_/_/  _/    _/    _/_/_/
     _/    _/  _/    _/  _/_/  _/_/  _/    _/  _/        _/  _/            _/
    _/    _/  _/_/_/_/  _/  _/  _/  _/_/_/_/    _/_/    _/_/          _/_/
   _/    _/  _/    _/  _/      _/  _/    _/        _/  _/  _/            _/
  _/_/_/    _/    _/  _/      _/  _/    _/  _/_/_/    _/    _/    _/_/_/
 
 Roters et al., Computational Materials Science 158:420–478, 2019
 https://doi.org/10.1016/j.commatsci.2018.04.030

 Version: v3.0.0-alpha2

 Compiled with: GCC version 9.3.0
 Compiler options: -cpp -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -iprefix /home/conda/feedstock_root/build_artifacts/damask_1608392739078/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/ -isysroot /home/conda/feedstock_root/build_artifacts/damask_1608392739078/_build_env/bin/../x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D DAMASKVERSION="v3.0.0-alpha2" -D Grid -D PETSc -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -auxbase-strip CMakeFiles/DAMASK_grid.dir/DAMASK_interface.f90.o -O2 -O2 -pedantic-errors -Wall -Wextra -Wcharacter-truncation -Wunderflow -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wconversion-extra -Wimplicit-procedure -Wno-unused-parameter -std=f2018 -ftree-vectorize -fstack-protector-strong -fno-plt -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/damask_1608392739078/work=/usr/local/src/conda/damask-3.0.0 -fdebug-prefix-map=/srv/conda/envs/notebook=/usr/local/src/conda-prefix -fopenmp -fPIE -ffree-line-length-132 -fimplicit-none -ffpe-summary=all -fdefault-real-8 -fdefault-double-8

 Compiled on: Dec 19 2020 at 15:51:03

 PETSc version: 3.13.6

 Date: 29/01/2021
 Time: 14:01:18

 Host name: jupyter-jan-2djanssen-2dpyiron-2ddamask-2dt6ccv81h
 User name: jovyan

 Command line call:      DAMASK_grid -l tensionX.load -g damask.geom
 Geometry argument:      damask.geom
 Loadcase argument:      tensionX.load

 Working directory:      /home/jovyan/elastic_pipeline/damask_mg_1_hdf5/damask_mg_1
 Geometry file:          damask.geom
 Loadcase file:          tensionX.load
 Solver job name:        damask_tensionX

 <<<+-  prec init  -+>>>
 Size of integer in bit:  32
   Maximum value:                 2147483647

 Size of float in bit:    64
   Maximum value:         0.180+309
   Minimum value:         0.223-307
   Epsilon value:         0.222E-15
   Decimal precision:     15

 <<<+-  IO init  -+>>>

 <<<+-  base64 init  -+>>>

 <<<+-  YAML_types init  -+>>>

 <<<+-  config init  -+>>>
 reading material.yaml

 <<<+-  math init  -+>>>
 size  of random seed:     33
 value of random seed:     -1634150703
 start of random sequence: 
                           0.93119579781899
                           0.47234670752052
                           0.80315545322790
                           0.72143379995039


 <<<+-  quaternions init  -+>>>

 <<<+-  rotations init  -+>>>
 Rowenhorst et al., Modelling and Simulation in Materials Science and Engineering 23:083501, 2015
 https://doi.org/10.1088/0965-0393/23/8/083501

 <<<+-  lattice init  -+>>>

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error                                        │
 │                        143                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ no value found for key                                              │
 │ mechanics                                                           │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘

 DAMASK terminated on:
 Date:               29/01/2021
 Time:               14:01:18
Note: The following floating-point exceptions are signalling: IEEE_INEXACT_FLAG
STOP 1
```

### CODE REVIEW

**Comment by jan-janssen** [comment]
@vitesh13 Can you help me here? It seems to be related to changes in the DAMASK input files.

**Comment by sharanroongta** [comment]
This is alpha 2, right?

**Comment by vitesh13** [comment]
From what I remember, it gets the latest python from the github repository and the DAMASK source code version is fixed at version alpha2?

**Comment by jan-janssen** [comment]
Yes, it is just the alpha 2 without the GitHub part. And I updated the key mech to:

```
homogenization:
  SX:
    mechanics: {type: none}

microstructure:
  - constituents:
      - fraction: 1.0
        orientation: [1.0, 0.0, 0.0, 0.0]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.7936696712125002, -0.28765777461664166, -0.3436487135089419, 0.4113964260949434]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.3986143167493579, -0.7014883552495493, 0.2154871765709027, 0.5500781677772945]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.28645844315788244, -0.022571491243423537, -0.467933059311115, -0.8357456192708106]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.33012772942625784, -0.6781865350268957, 0.6494525351030648, 0.09638521992649676]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.43596817439583935, -0.5982537129781701, 0.046599032277502436, 0.6707106499919265]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.169734823419553, -0.699615227367322, -0.6059581215838098, -0.33844257746495854]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.9698864809294915, 0.1729052643205874, -0.15948307917616958, 0.06315956884687175]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.46205660912967883, 0.3105054068891252, -0.617849551030653, 0.555294529545738]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.4512443497461787, -0.7636045534540555, -0.04739348426715133, -0.45939142396805815]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.2161856212656443, -0.6581450184826598, -0.5498086209601588, 0.4667112513346289]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.8753220715350803, -0.4561599367657419, -0.13298279533852678, -0.08969369719975541]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.11908260752431069, 0.18266024809834172, -0.7144822594012615, -0.664807992845101]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.751104669484278, 0.5585633382623958, -0.34579336397009175, 0.06538900566860861]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.08740438971703973, 0.8991264096610437, -0.4156704205935976, 0.10559485570696363]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.5584325870096193, 0.6016408353068798, -0.14280340445801173, 0.5529814994483859]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.4052725440888093, 0.25253073423599154, 0.5693263597910454, -0.669215876471182]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.7570164606888676, 0.15265448024694664, -0.5998021466848317, 0.20942796551297105]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.6987659297138081, -0.132172211261028, -0.19693254724422338, 0.6748883269678543]
        phase: Aluminum
    homogenization: SX
  - constituents:
      - fraction: 1.0
        orientation: [0.7729330445886478, 0.21682179052722322, -0.5207379472917645, 0.2905078484066341]
        phase: Aluminum
    homogenization: SX

phase:
  Aluminum:
    elasticity: {type: hooke, C_11: 110198207740.84601, C_12: 61613523554.16192, C_44: 32687117772.35353}
    generic:
      output: [F, P, Fe, Fp, Lp]
    lattice: fcc
    plasticity:
      N_sl: [12]
      a_sl: 2.25
      atol_xi: 1.0
      dot_gamma_0_sl: 0.001
      h_0_sl_sl: 75e6
      h_sl_sl: [1, 1, 1.4, 1.4, 1.4, 1.4]
      n_sl: 20
      output: [xi_sl]
      type: phenopowerlaw
      xi_0_sl: [31e6]
      xi_inf_sl: [63e6]

```

**Comment by vitesh13** [comment]
I think the file should in general work now

**Comment by vitesh13** [comment]
I am attaching an example file here for reference (in case I missed something in it):

```
homogenization:
  SX:
    N_constituents: 1
    mechanics: {type: none}

material:
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [1.0, 0.0, 0.0, 0.0]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.7936696712125002, -0.28765777461664166, -0.3436487135089419, 0.4113964260949434]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.3986143167493579, -0.7014883552495493, 0.2154871765709027, 0.5500781677772945]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.28645844315788244, -0.022571491243423537, -0.467933059311115, -0.8357456192708106]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.33012772942625784, -0.6781865350268957, 0.6494525351030648, 0.09638521992649676]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.43596817439583935, -0.5982537129781701, 0.046599032277502436, 0.6707106499919265]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.169734823419553, -0.699615227367322, -0.6059581215838098, -0.33844257746495854]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.9698864809294915, 0.1729052643205874, -0.15948307917616958, 0.06315956884687175]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.46205660912967883, 0.3105054068891252, -0.617849551030653, 0.555294529545738]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.4512443497461787, -0.7636045534540555, -0.04739348426715133, -0.45939142396805815]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.2161856212656443, -0.6581450184826598, -0.5498086209601588, 0.4667112513346289]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.8753220715350803, -0.4561599367657419, -0.13298279533852678, -0.08969369719975541]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.11908260752431069, 0.18266024809834172, -0.7144822594012615, -0.664807992845101]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.751104669484278, 0.5585633382623958, -0.34579336397009175, 0.06538900566860861]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.08740438971703973, 0.8991264096610437, -0.4156704205935976, 0.10559485570696363]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.5584325870096193, 0.6016408353068798, -0.14280340445801173, 0.5529814994483859]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.4052725440888093, 0.25253073423599154, 0.5693263597910454, -0.669215876471182]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.7570164606888676, 0.15265448024694664, -0.5998021466848317, 0.20942796551297105]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.6987659297138081, -0.132172211261028, -0.19693254724422338, 0.6748883269678543]
  - homogenization: SX
    constituents:
      - phase: Aluminum
        fraction: 1.0
        O: [0.7729330445886478, 0.21682179052722322, -0.5207379472917645, 0.2905078484066341]

phase:
  Aluminum:
    lattice: cF
    mechanics:
      output: [F, P, F_e, F_p, L_p, O]
      elasticity: {C_11: 106.75e9, C_12: 60.41e9, C_44: 28.34e9, type: hooke}
      plasticity:
        N_sl: [12]
        a_sl: 2.25
        atol_xi: 1.0
        dot_gamma_0_sl: 0.001
        h_0_sl_sl: 75e6
        h_sl_sl: [1, 1, 1.4, 1.4, 1.4, 1.4]
        n_sl: 20
        output: [xi_sl]
        type: phenopowerlaw
        xi_0_sl: [31e6]
        xi_inf_sl: [63e6]

```

**Comment by vitesh13** [comment]
But if the source files refer to alpha2 version, then maybe the geometry files have changed to .vtr files
And also load file has changed to yaml format

**Comment by jan-janssen** [comment]
You are right, now I get: 

```
 <<<+-  parallelization init  -+>>>
 MPI processes:   1
 Could not determine value of $DAMASK_NUM_THREADS
 DAMASK_NUM_THREADS:  1

 <<<+-  DAMASK_interface init  -+>>>
 
      _/_/_/      _/_/    _/      _/    _/_/      _/_/_/  _/    _/    _/_/_/
     _/    _/  _/    _/  _/_/  _/_/  _/    _/  _/        _/  _/            _/
    _/    _/  _/_/_/_/  _/  _/  _/  _/_/_/_/    _/_/    _/_/          _/_/
   _/    _/  _/    _/  _/      _/  _/    _/        _/  _/  _/            _/
  _/_/_/    _/    _/  _/      _/  _/    _/  _/_/_/    _/    _/    _/_/_/
 
 Roters et al., Computational Materials Science 158:420–478, 2019
 https://doi.org/10.1016/j.commatsci.2018.04.030

 Version: v3.0.0-alpha2

 Compiled with: GCC version 9.3.0
 Compiler options: -cpp -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -I /srv/conda/envs/notebook/include -iprefix /home/conda/feedstock_root/build_artifacts/damask_1608392739078/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/ -isysroot /home/conda/feedstock_root/build_artifacts/damask_1608392739078/_build_env/bin/../x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D DAMASKVERSION="v3.0.0-alpha2" -D Grid -D PETSc -isystem /srv/conda/envs/notebook/include -march=nocona -mtune=haswell -auxbase-strip CMakeFiles/DAMASK_grid.dir/DAMASK_interface.f90.o -O2 -O2 -pedantic-errors -Wall -Wextra -Wcharacter-truncation -Wunderflow -Wsuggest-attribute=pure -Wsuggest-attribute=noreturn -Wconversion-extra -Wimplicit-procedure -Wno-unused-parameter -std=f2018 -ftree-vectorize -fstack-protector-strong -fno-plt -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/damask_1608392739078/work=/usr/local/src/conda/damask-3.0.0 -fdebug-prefix-map=/srv/conda/envs/notebook=/usr/local/src/conda-prefix -fopenmp -fPIE -ffree-line-length-132 -fimplicit-none -ffpe-summary=all -fdefault-real-8 -fdefault-double-8

 Compiled on: Dec 19 2020 at 15:51:03

 PETSc version: 3.13.6

 Date: 29/01/2021
 Time: 14:49:37

 Host name: jupyter-jan-2djanssen-2dpyiron-2ddamask-2dmeau6kr5
 User name: jovyan

 Command line call:      DAMASK_grid -l tensionX.load -g damask.geom
 Geometry argument:      damask.geom
 Loadcase argument:      tensionX.load

 Working directory:      /home/jovyan/elastic_pipeline/damask_mg_2_hdf5/damask_mg_2
 Geometry file:          damask.geom
 Loadcase file:          tensionX.load
 Solver job name:        damask_tensionX

 <<<+-  prec init  -+>>>
 Size of integer in bit:  32
   Maximum value:                 2147483647

 Size of float in bit:    64
   Maximum value:         0.180+309
   Minimum value:         0.223-307
   Epsilon value:         0.222E-15
   Decimal precision:     15

 <<<+-  IO init  -+>>>

 <<<+-  base64 init  -+>>>

 <<<+-  YAML_types init  -+>>>

 <<<+-  config init  -+>>>
 reading material.yaml

 <<<+-  math init  -+>>>
 size  of random seed:     33
 value of random seed:     1200836154
 start of random sequence: 
                           0.70743610128384
                           0.90098386447735
                           0.85650063660974
                           0.52475151620175


 <<<+-  quaternions init  -+>>>

 <<<+-  rotations init  -+>>>
 Rowenhorst et al., Modelling and Simulation in Materials Science and Engineering 23:083501, 2015
 https://doi.org/10.1088/0965-0393/23/8/083501

 <<<+-  lattice init  -+>>>

 <<<+-  HDF5_Utilities init  -+>>>

 <<<+-  results init  -+>>>
 Diehl et al., Integrating Materials and Manufacturing Innovation 6(1):83–91, 2017
 https://doi.org/10.1007/s40192-017-0084-5


 <<<+-  discretization_grid init  -+>>>

 ┌─────────────────────────────────────────────────────────────────────┐
 │                        error                                        │
 │                        844                                          │
 ├─────────────────────────────────────────────────────────────────────┤
 │ invalid VTR file                                                    │
 │ material data not found                                             │
 │                                                                     │
 └─────────────────────────────────────────────────────────────────────┘

 DAMASK terminated on:
 Date:               29/01/2021
 Time:               14:49:38
Note: The following floating-point exceptions are signalling: IEEE_INEXACT_FLAG
STOP 1
```

**Comment by sharanroongta** [comment]
yup..soo
1. Convert .geom to .vtr as:
    damask.Grid.load_ASCII('filename.geom').save('filename')
2. Similary load file should move to yaml

**Comment by sharanroongta** [comment]
https://github.com/eisenforschung/DAMASK/blob/v3.0.0-alpha2/examples/SpectralMethod/Polycrystal/tensionX.yaml

Load file in yaml

**Comment by jan-janssen** [comment]
I am now I able to run the calculation, but the post processing fails:

```
stresses, strains = [], []
for job in job_lst: 
    damask_results = job.output
    damask_results.add_stress_Cauchy()
    damask_results.add_stretch_tensor()
    damask_results.add_equivalent_Mises('sigma')
    damask_results.add_equivalent_Mises('epsilon_V^0.0(F)')
    damask_results.add_calculation('avg_sigma',"np.average(#sigma_vM#)")
    damask_results.add_calculation('avg_epsilon',"np.average(#epsilon_V^0.0(F)_vM#)")
    damask_results.save_VTK(['sigma','epsilon_V^0.0(F)','sigma_vM','epsilon_V^0.0(F)_vM'])
    stresses.append(job.eval_stress())
    strains.append(job.eval_strain())
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-25-f80777904526> in <module>
     10     damask_results.save_VTK(['sigma','epsilon_V^0.0(F)','sigma_vM','epsilon_V^0.0(F)_vM'])
     11     stresses.append(job.eval_stress())
---> 12     strains.append(job.eval_strain())

~/damaskjob.py in eval_strain(self)
    128             hdf = h5py.File(d.fname)
    129             for count,path in enumerate(stress_path):
--> 130                 strain[count] = np.array(hdf[path.split('avg_sigma')[0]     + 'avg_epsilon'])
    131 
    132             return strain

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/srv/conda/envs/notebook/lib/python3.7/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    286                 raise ValueError("Invalid HDF5 object reference")
    287         else:
--> 288             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    289 
    290         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'avg_epsilon' doesn't exist)"
```

**Comment by sharanroongta** [comment]
add_stretch_tensor()  ----> add_strain()

**Comment by jan-janssen** [comment]
Thanks a lot - now everything seems to work

**Pull request closed without merging**
